### ISSUE TITLE
npm run serve fails

### ISSUE THREAD

**Issue by connorjburton** [nolanlawson/pokedex.org#22]
On windows 10, latest node. Running ```npm run serve```, also tried running ```npm run serve``` after ```npm install```

```
{lamb} npm run serve                                                      
                                                                          
pokedex@1.0.0 serve C:\xampp\htdocs\pokedex.org                         
babel-node bin/dev-server.js
events.js:141                                                             
hrow er; // Unhandled 'error' event                                
Error: spawn ../node_modules/.bin/pouchdb-server ENOENT                   
    at exports._errnoException (util.js:874:11)                           
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:
    at onErrorNT (internal/child_process.js:344:16)                       
    at doNTCallback2 (node.js:441:9)                                      
    at process._tickDomainCallback (node.js:396:17)
npm ERR! Windows_NT 10.0.10240                                            
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Conn
es\\npm\\bin\\npm-cli.js" "run" "serve"                                   
npm ERR! node v4.2.2                                                      
npm ERR! npm  v3.4.1                                                      
npm ERR! code ELIFECYCLE                                                  
npm ERR! pokedex@1.0.0 serve: `babel-node bin/dev-server.js`              
npm ERR! Exit status 1                                                    
npm ERR!                                                                  
npm ERR! Failed at the pokedex@1.0.0 serve script 'babel-node bin/dev-serv
npm ERR! Make sure you have the latest version of node.js and npm installe
npm ERR! If you do, this is most likely a problem with the pokedex package
npm ERR! not with npm itself.                                             
npm ERR! Tell the author that this fails on your system:                  
npm ERR!     babel-node bin/dev-server.js                                  ```

**Comment by nolanlawson** [comment]
Did you `npm install` first?

**Comment by connorjburton** [comment]
Yep, my ```npm list --depth=0``` is:

```
{lamb} npm list --depth=0
pokedex@1.0.0 C:\xampp\htdocs\pokedex.org
├── autoprefixer@6.1.1
├── babel@5.8.34
├── babel-eslint@4.1.6
├── babelify@6.4.0
├── bluebird@2.10.2
├── browserify@11.2.0
├── bundle-collapser@1.2.1
├── clean-css@3.4.8
├── color@0.10.1
├── concat-stream@1.5.1
├── cp@0.2.0
├── debounce@1.0.0
├── envify@3.4.0
├── eslint@1.10.1
├── execall@1.0.0
├── factor-bundle@2.5.0
├── html-minifier@1.0.0
├── html2hscript@1.2.1
├── htmltidy@0.0.6
├── http-server@0.8.5
├── lie@3.0.1
├── localforage@1.3.0
├── lodash@3.10.1
├── memdown@1.1.0
├── memorystream@0.3.1
├── minify-css-stream@0.1.0
├── mkdirp@0.5.1
├── ncp@2.0.0
├── node-fetch@1.3.3
├── node-watch@0.3.4
├── postcss@5.0.12
├── pouch-sync-cli@1.0.0
├── pouchdb@5.1.0
├── pouchdb-find@0.6.0
├── pouchdb-load@1.4.3
├── pouchdb-replication-stream@1.2.5
├── pouchdb-server@1.0.0
├── pouchdb-upsert@1.1.3
├── regenerator@0.8.42
├── rimraf@2.4.4
├── semver@5.1.0
├── serviceworker-cache-polyfill@3.0.0
├── short-revs@1.0.0
├── stream-to-promise@1.0.4
├── stripify@3.0.0
├── through@2.3.8
├── transform-pouch@1.0.2
├── uglify-js@2.6.1
├── uglify-stream@1.1.0
├── uglifyify@3.0.1
├── vdom-as-json@1.0.8
├── vdom-serialized-patch@1.0.2
├── vdom-to-html@2.2.0
├── virtual-dom@2.1.1
├── watchify@3.6.1
└── zpad@0.5.0
```

**Comment by nolanlawson** [comment]
So the issue is that `../node_modules/.bin/pouchdb-server` is giving ENOENT, meaning the file is not found. On *nix machines the file is there; is the file structure different for Node on Windows? Can you check your .bin directory?

**Comment by connorjburton** [comment]
I have checked and it seems to be there, I have attached screenshots. I also tried to run cmder as administrator and it didn't make a difference.

![pouch-db](https://cloud.githubusercontent.com/assets/10538031/11437442/a925e3a0-94e5-11e5-8ccf-d3f9bbb12a81.png)
![pouch-db-vim](https://cloud.githubusercontent.com/assets/10538031/11437443/a92db95e-94e5-11e5-9e23-9d01337a2605.png)

**Comment by samccone** [comment]
this looks like an issue you might want to file with pouchdb, this kind of error is not so weird to run into in windows land :(

**Comment by nolanlawson** [comment]
So [here](https://github.com/pouchdb/pouchdb-server/blob/79715469290b1a663136341c48fe4f2fe9f2f862/bin/pouchdb-server) is the executable for pouchdb-server, and [here](https://github.com/pouchdb/pouchdb-server/blob/79715469290b1a663136341c48fe4f2fe9f2f862/package.json#L14-L16) is how we declare it as a "bin" executable in the package.json. This is the way you do it, right? Is there something wrong with the shebang? Or maybe on Windows, the "bin"s go in a different directory.

An alternative solution is to add a new npm script that just runs `pouchdb-server` without specifying `.bin`.

**Comment by connorjburton** [comment]
I'll be switching to Mac for my home setup next couple of weeks so its not a huge deal but I'd be interested if other windows users are experiencing the same issue.

Will play about with it next week.

**Comment by nolanlawson** [comment]
On your Windows machine, can you try `npm install -g pouchdb-server` and see if you can then run `pouchdb-server`? Trying to figure out whether it's an issue with PouchDB Server or with this lib, and I don't have a Windows machine.

**Comment by connorjburton** [comment]
Did a ```npm install -g pouchdb-server```, that worked alright, then did a ```pouchdb-server``` and also seemed to work okay:
```
C:\xampp\htdocs\pokedex.org {git}
{lamb} pouchdb-server
[info] pouchdb-server has started on http://127.0.0.1:5984/
[info] navigate to http://127.0.0.1:5984/_utils for the Fauxton UI.
```

**Comment by nolanlawson** [comment]
^ My guess is it's an issue with the CWD then; can you update to master and try again?

**Comment by connorjburton** [comment]
Get the following:

```
{lamb} npm run serve

> pokedex@1.0.0 serve C:\xampp\htdocs\pokedex.org
> babel-node bin/dev-server.js

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\xampp\htdocs\pokedex.org\bin/../node_modules/.bin/pouchdb-server ENOENT
```

**Comment by nolanlawson** [comment]
Ahhh, I see what it is. It's because Windows uses `\` but *nix uses `/`.

**Comment by connorjburton** [comment]
AFAIK windows is / agnostic, it will work either way, I went and manually changed my dev-server.js to point to the path directly and it still failed. I am lost now, it must be a permissions thing.

```
{lamb} npm run serve                                                               
                                                                                   
> pokedex@1.0.0 serve C:\xampp\htdocs\pokedex.org                                  
> babel-node bin/dev-server.js                                                     
                                                                                   
events.js:141                                                                      
      throw er; // Unhandled 'error' event                                         
      ^                                                                            
                                                                                   
Error: spawn C:\xampp\htdocs\pokedex.org\node_modules\.bin\pouchdb-server ENOENT   
    at exports._errnoException (util.js:874:11)                                    
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)      
    at onErrorNT (internal/child_process.js:344:16)                                
    at doNTCallback2 (node.js:441:9)                                               
    at process._tickDomainCallback (node.js:396:17)
```

**Comment by connorjburton** [comment]
Okay I got it, ```node_modules\.bin\``` is a folder of symlinks, apparently windows doesn't like symlinks here. (See http://askubuntu.com/questions/269727/npm-errors-when-installing-packages-on-windows-share)

If I reference ```'C:\xampp\htdocs\pokedex.org\node_modules\pouchdb-server\bin\pouchdb-server',``` it works.

Although now I get a bunch of SyntaxErrors to do with ```async```, ```new```, see example of first one I encounter (many more)

```
C:\xampp\htdocs\pokedex.org {git}                                                                              
{lamb} npm run serve                                                                                           
                                                                                                               
> pokedex@1.0.0 serve C:\xampp\htdocs\pokedex.org                                                              
> babel-node bin/dev-server.js                                                                                 
                                                                                                               
C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\inde
x.js:540                                                                                                       
      throw err;                                                                                               
      ^                                                                                                        
                                                                                                               
SyntaxError: C:/xampp/htdocs/pokedex.org/bin/dev-server.js: Unexpected token (28:6)                            
  26 | }                                                                                                       
  27 |                                                                                                         
> 28 | async function doIt() {                                                                                 
     |       ^                                                                                                 
  29 |                                                                                                         
  30 |   startPouchServer();                                                                                   
  31 |                                                                                                         
    at Parser.pp.raise (C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\node
_modules\babylon\lib\parser\location.js:22:13)                                                                 
    at Parser.pp.unexpected (C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core
\node_modules\babylon\lib\parser\util.js:91:8)                                                                 
    at Parser.pp.semicolon (C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\
node_modules\babylon\lib\parser\util.js:78:38)                                                                 
    at Parser.pp.parseExpressionStatement (C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modu
les\babel-core\node_modules\babylon\lib\parser\statement.js:471:8)                                             
    at Parser.pp.parseStatement (C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-
core\node_modules\babylon\lib\parser\statement.js:162:17)                                                      
    at Parser.pp.parseBlockBody (C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-
core\node_modules\babylon\lib\parser\statement.js:527:25)                                                      
    at Parser.pp.parseTopLevel (C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-c
ore\node_modules\babylon\lib\parser\statement.js:29:8)                                                         
    at Parser.parse (C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\node_mo
dules\babylon\lib\parser\index.js:96:17)                                                                       
    at Object.parse (C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\node_mo
dules\babylon\lib\index.js:44:50)                                                                              
    at File.parse (C:\Users\Connor\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\trans
formation\file\index.js:472:24)                                                                                
                                                                                                               
npm ERR! Windows_NT 10.0.10240                                                                                 
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Connor\\AppData\\Roaming\\npm\\node_modul
es\\npm\\bin\\npm-cli.js" "run" "serve"                                                                        
npm ERR! node v4.2.2                                                                                           
npm ERR! npm  v3.5.1                                                                                           
npm ERR! code ELIFECYCLE                                                                                       
npm ERR! pokedex@1.0.0 serve: `babel-node bin/dev-server.js`                                                   
npm ERR! Exit status 1                                                                                         
npm ERR!                                                                                                       
npm ERR! Failed at the pokedex@1.0.0 serve script 'babel-node bin/dev-server.js'.                              
npm ERR! Make sure you have the latest version of node.js and npm installed.                                   
npm ERR! If you do, this is most likely a problem with the pokedex package,                                    
npm ERR! not with npm itself.                                                                                  
npm ERR! Tell the author that this fails on your system:                                                       
npm ERR!     babel-node bin/dev-server.js                                                                      
npm ERR! You can get information on how to open an issue for this project with:                                
npm ERR!     npm bugs pokedex                                                                                  
npm ERR! Or if that isn't available, you can get their info via:                                               
npm ERR!     npm owner ls pokedex                                                                              
npm ERR! There is likely additional logging output above.                                                      
                                                                                                               
npm ERR! Please include the following file with any support request:                                           
npm ERR!     C:\xampp\htdocs\pokedex.org\npm-debug.log
```

**Comment by awayken** [comment]
I'm running into this a year later. I'm running Windows 10, Node v6.9.1, npm v4.0.1.

```bash
npm run serve

> pokedex@7.0.0 serve C:\Sites\pokedex.org
> babel-node bin/dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Sites\pokedex.org\node_modules\pouchdb-server\bin\pouchdb-server ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mrausch\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.1
npm ERR! code ELIFECYCLE
npm ERR! pokedex@7.0.0 serve: `babel-node bin/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokedex@7.0.0 serve script 'babel-node bin/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokedex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node bin/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokedex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokedex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Sites\pokedex.org\npm-debug.log
```

I'd love to jump in and help fix this, but Pokedex has changed a lot since this ticket was filed. Does anyone have a sense of what the current state of this issue is?

**Comment by nolanlawson** [comment]
This appears to be a Windows issue, which is a bit embarrassing because I work for Microsoft now. 😅  Most likely I just need to test the script on Windows and tweak it to handle Windows filepaths correctly. Alternatively, are you sure that PouchDB Server installed correctly? You may need to run `npm install -g windows-build-tools` in an elevated PowerShell, see: https://www.npmjs.com/package/windows-build-tools

**Comment by awayken** [comment]
@nolanlawson I installed the `windows-build-tools`, deleted the `node_modules` folder for Pokedex and ran `npm install` again. Then I ran `npm run serve` but I got the same result. Just FYI.

**Comment by sonicviz** [comment]
Tried running on Win 10 and fails:

npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Paul\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve' ]
2 info using npm@3.7.5
3 info using node@v4.5.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle pokedex@8.0.0~preserve: pokedex@8.0.0
6 silly lifecycle pokedex@8.0.0~preserve: no script for preserve, continuing
7 info lifecycle pokedex@8.0.0~serve: pokedex@8.0.0
8 verbose lifecycle pokedex@8.0.0~serve: unsafe-perm in lifecycle true
9 verbose lifecycle pokedex@8.0.0~serve: PATH: C:\Users\Paul\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;G:\Node Projects\pokedex.org-master\node_modules\.bin;D:\Program Files\nodejs;G:\Program Files\NVIDIA\CUDA\bin;G:\Program Files\NVIDIA\CUDA\libnvvp;C:\ProgramData\Oracle\Java\javapath;D:\Program Files (x86)\Eazfuscator.NET;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Windows Live\Shared;D:\Program Files\TortoiseSVN\bin;D:\Program Files (x86)\Android\android-sdk\tools;C:\Program Files (x86)\VoiceAge\Common;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;d:\Program Files\doxygen\bin;E:\Unity3D\Design Notes\CSharp\Amazon\IAMCli-1.5.0\bin;D:\OpenSSL-Win64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Calibre2\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;d:\Program Files (x86)\Git\cmd;d:\Program Files (x86)\Git\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Python27;D:\Python27\Scripts;C:\Users\Paul\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;D:\wamp\bin\php\php5.5.12;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Skype\Phone\;D:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;D:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;d:\Program Files (x86)\Heroku\bin;C:\Users\Paul\AppData\Local\.meteor\;d:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Paul\AppData\Local\Pandoc\;C:\Users\Paul\AppData\Local\atom\bin;C:\Users\Paul\AppData\Roaming\npm;C:\Users\Paul\AppData\Local\Microsoft\WindowsApps;D:\Users\Paul\AppData\Local\Android\sdk\platform-tools
10 verbose lifecycle pokedex@8.0.0~serve: CWD: G:\Node Projects\pokedex.org-master
11 silly lifecycle pokedex@8.0.0~serve: Args: [ '/d /s /c', 'async-node bin/dev-server.js' ]
12 silly lifecycle pokedex@8.0.0~serve: Returned: code: 1  signal: null
13 info lifecycle pokedex@8.0.0~serve: Failed to exec serve script
14 verbose stack Error: pokedex@8.0.0 serve: `async-node bin/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Paul\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Paul\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid pokedex@8.0.0
16 verbose cwd G:\Node Projects\pokedex.org-master
17 error Windows_NT 10.0.14393
18 error argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Paul\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
19 error node v4.5.0
20 error npm  v3.7.5
21 error code ELIFECYCLE
22 error pokedex@8.0.0 serve: `async-node bin/dev-server.js`
22 error Exit status 1
23 error Failed at the pokedex@8.0.0 serve script 'async-node bin/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pokedex package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     async-node bin/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pokedex
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pokedex
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Console log:
G:\Node Projects\pokedex.org-master>npm run serve

> pokedex@8.0.0 serve G:\Node Projects\pokedex.org-master
> async-node bin/dev-server.js

G:\Node Projects\pokedex.org-master\bin\dev-server.js:91
  var allPromises = [...loadPromises, buildPromise, serverPromise];
                     ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._compile (G:\Node Projects\pokedex.org-master\node_modules\async-to-gen\register.js:37:23)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (G:\Node Projects\pokedex.org-master\node_modules\async-to-gen\register.js:40:5)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at Object.<anonymous> (G:\Node Projects\pokedex.org-master\node_modules\async-to-gen\async-node:98:10)
    at Module._compile (module.js:409:26)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Paul\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
npm ERR! node v4.5.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! pokedex@8.0.0 serve: `async-node bin/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokedex@8.0.0 serve script 'async-node bin/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokedex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     async-node bin/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokedex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokedex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\Node Projects\pokedex.org-master\npm-debug.log

**Comment by FourierEnvy** [comment]
Also have the same logs, in Win10:

> pokedex@9.0.0 serve C:\Users\Marcus\Desktop\ReactProjects\pokedex.org
> async-node bin/dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Marcus\Desktop\ReactProjects\pokedex.org\node_modules\pouchdb-server\bin\pouchdb-server ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pokedex@9.0.0 serve: `async-node bin/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokedex@9.0.0 serve script 'async-node bin/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokedex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     async-node bin/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokedex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokedex
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marcus\AppData\Roaming\npm-cache\_logs\2017-03-26T04_45_41_641Z-debug.log
